### ISSUE TITLE
Error loading Module

### ISSUE THREAD

**Issue by Paul75** [samsonasik/SanAuth#3]
Hello,

I download the module and add to my module directory. When I go to my website it mailed and do this :

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (SanAuth) could not be initialized.' in /srv/http/printaplus/hall/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:195 Stack trace: #0 /srv/http/printaplus/hall/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(169): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 /srv/http/printaplus/hall/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(96): Zend\ModuleManager\ModuleManager->loadModule('SanAuth') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 /srv/http/printaplus/hall/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 /srv/http/printaplus/hall/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('loadModules', Object(Zend\ModuleManag in /srv/http/printaplus/hall/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 195

Thanks for help

**Comment by samsonasik** [comment]
you need to copy the module to `module/` directory, setup Db adapter with 'Zend\Db\Adapter\Adapter' key ( read the docs; http://zf2.readthedocs.org/en/latest/user-guide/database-and-models.html ), create user table https://github.com/samsonasik/SanAuth/blob/master/Module.php#L57, and follow the readme https://github.com/samsonasik/SanAuth/blob/master/README.md
